# Default values for ephemeral-grafana.
# Simplified configuration for single-use ephemeral instances.

# Container image configuration
image:
  repository: us-central1-docker.pkg.dev/rhiza-shared/sheerwater/grafana
  tag: v1.0.4
  pullPolicy: IfNotPresent
  # Uses the chart appVersion as the image tag (single source of truth)

# Service configuration  
service:
  type: ClusterIP
  port: 3000

# Ingress configuration (overridden by ApplicationSet)
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []


plugins:
- gapit-htmlgraphics-panel
- marcusolsson-dynamictext-panel
- nline-plotlyjs-panel

# Grafana application configuration
grafana:
  config:
    server:
      # NOTE: this value is overwritten by the argocd application set with the PR based url.
      root_url: http://localhost:3000
    auth:
      # TODO: configure github auth for the ephemeral grafana instances
      anonymous:
        enabled: true
        org_role: Admin
    security:
      admin_password: changeme

# this is the password for the admin user
# # This should be overridden via Helm --set admin_password=<value> or --set-string admin_password=<value>
# admin_password: "changeme"


# adminUser: admin
# adminPassword: changeme

# # Use an existing secret for the admin user.
# admin:
#   ## Name of the secret. Can be templated.
#   existingSecret: "grafana-admin-password"
#   userKey: admin-user
#   passwordKey: admin-password