[project]
name = "sheerwater-benchmarking"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Joshua Adkins", email = "josh@nline.io" }
]
dependencies = [
    "dask==2024.7.0",
    "dask[complete]",
    "coiled",
    "httplib2",
    "s3fs",
    "google-api-python-client",
    "proto-plus==1.24.0.dev1",
    "google-cloud-storage",
    "cryptography",
    "ipykernel",
    "jupyterlab",
    "xarray",
    "matplotlib",
    "geopandas",
    "rioxarray",
    "notebook",
    "jupytext",
    "dask-kubernetes>=2024.5.0",
    "gcsfs",
    "zarr",
    "h5py",
    "netcdf4",
    "h5netcdf",
    "scipy",
    "requests",
    "ecmwf-api-client",
]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/sheerwater_benchmarking"]
