# Default values for sheerwater-benchmarking.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
grafana:
  image: 
    repository: us-central1-docker.pkg.dev/rhiza-shared/sheerwater/grafana
    tag: v1.0.4

  admin_password: pass

  smtp:
    user: apikey
    password: key
    host: smtp.sendgrid.net:587
    from_address: info@rhizaresearch.org
    from_name: Sheerwater Benchmarking Project

  pv:
    name: name
    size: 10GiB

  domain_name: domain.com
  ip_name: gcloud-ip
  resources:
    requests:
      cpu: 250m
      memory: 1Gi


postgres:
  image: 
    repository: postgres
    tag: "15.8"

  pv:
    name: name
    size: 10GiB

  tailscale: true

  admin_password: pass

  resources:
    requests:
      cpu: 250m
      memory: 1Gi

terracotta:
  image: 
    repository: ghcr.io/rhiza-research/terracotta
    tag: "v0.0.14"

  tailscale: true

  driver_path: postgresql://postgres:5432/terracotta

  multiprocessing_workers: 6

  sql_user: read
  sql_password: read_password

  domain_name: domain.com
  ip_name: gcloud-ip

  pv:
    name: name
    size: 50GiB

  resources:
    requests:
      cpu: 2000m
      memory: 500Mi

