{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ephemeral-grafana.fullname" . }}-cert-copier
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ephemeral-grafana.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ephemeral-grafana.fullname" . }}-cert-copier
  labels:
    {{- include "ephemeral-grafana.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ephemeral-grafana.fullname" . }}-cert-copier
  labels:
    {{- include "ephemeral-grafana.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
subjects:
- kind: ServiceAccount
  name: {{ include "ephemeral-grafana.fullname" . }}-cert-copier
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "ephemeral-grafana.fullname" . }}-cert-copier
  apiGroup: rbac.authorization.k8s.io
{{- end }} 