apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ephemeral-grafana.fullname" . }}-config
  labels:
    {{- include "ephemeral-grafana.labels" . | nindent 4 }}
data:
  grafana.ini: |
    [server]
    root_url = {{ .Values.grafana.config.server.root_url }}
    serve_from_sub_path = true

    [auth.anonymous]
    enabled = {{ .Values.grafana.config.auth.anonymous.enabled }}
    org_role = {{ .Values.grafana.config.auth.anonymous.org_role }}

    [auth.generic_oauth]
    {{- with .Values.grafana.config.auth.generic_oauth }}
    enabled = true
    name = Google
    client_id = {{ .client_id | quote }}
    client_secret = {{ .client_secret | quote }}
    scopes = {{ (.scopes | default "openid email profile") | quote }}
    auth_url = {{ (.auth_url | default "https://accounts.google.com/o/oauth2/v2/auth") | quote }}
    token_url = {{ (.token_url | default "https://oauth2.googleapis.com/token") | quote }}
    {{- if .redirect_url }}
    redirect_url = {{ .redirect_url | quote }}
    {{- end }}
    use_pkce = {{ (.use_pkce | default true) }}
    allow_sign_up = {{ (.allow_sign_up | default true) }}
    login_attribute_path = {{ (.login_attribute_path | default "email") | quote }}
    name_attribute_path = {{ (.name_attribute_path | default "coalesce(join(' ', [given_name, family_name]), preferred_username)") | quote }}
    role_attribute_path = {{ (.role_attribute_path | default "contains(realm_access.roles[], 'grafana_admin') && 'Admin' || contains(realm_access.roles[], 'grafana_editor') && 'Editor' || 'Viewer'") | quote }}
    {{- end }}

    [security]
    admin_user = admin # {{ .Values.grafana.config.security.admin_user | quote }}
    admin_password = admin # {{ .Values.grafana.config.security.admin_password | quote }}

    [plugins]
    preinstall = gapit-htmlgraphics-panel,marcusolsson-dynamictext-panel,nline-plotlyjs-panel