apiVersion: v2
name: ephemeral-grafana-applicationset
description: A Helm chart for Argo CD ApplicationSet that manages ephemeral Grafana instances
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies: []

keywords:
  - grafana
  - argocd
  - applicationset
  - ephemeral
  - pull-request

maintainers:
  - name: Rhiza Research
    email: tristan@rhizaresearch.org

home: https://github.com/rhiza-research/infrastructure
sources:
  - https://github.com/rhiza-research/infrastructure 