apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sheerwater-benchmarking.fullname" . }}-grafana
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.grafana.ip_name }}
    kuberenetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: {{ include "sheerwater-benchmarking.fullname" . }}-grafana
    networking.gke.io/v1beta1.FrontendConfig: {{ include "sheerwater-benchmarking.fullname" . }}-grafana
spec:
  defaultBackend:
    service:
      name: {{ include "sheerwater-benchmarking.fullname" . }}-grafana
      port:
        number: 80
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ include "sheerwater-benchmarking.fullname" . }}-grafana
spec:
  redirectoToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT

