apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sheerwater-benchmarking.fullname" . }}-grafana-secrets
  labels:
    app: {{ include "sheerwater-benchmarking.name" . }}-grafana
    release: {{ .Release.Name }}
type: Opaque
data:
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.grafana.admin_password | b64enc | quote }}
  GF_AUTH_GOOGLE_CLIENT_ID: {{ .Values.grafana.google_oauth.client_id | b64enc | quote }}
  GF_AUTH_GOOGLE_CLIENT_SECRET: {{ .Values.grafana.google_oauth.client_secret | b64enc | quote }}
  GF_SMTP_PASSWORD: {{ .Values.grafana.smtp.password | b64enc | quote }}

