apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sheerwater-benchmarking.fullname" . }}-grafana
  labels:
    app: {{ include "sheerwater-benchmarking.name" . }}-grafana
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "sheerwater-benchmarking.name" . }}-grafana
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        timestamp: '{{ now | date "2006-01-02T15:04:05" }}'
      labels:
        app: {{ include "sheerwater-benchmarking.name" . }}-grafana
        release: {{ .Release.Name }}
    spec:
      initContainers:
      - name: volume-permissions
        image: busybox
        command: ['sh', '-c', 'chown -R 472:472 /var/lib/grafana']
        envFrom:
          - secretRef:
              name: {{ include "sheerwater-benchmarking.fullname" . }}-grafana-secrets
        volumeMounts:
        - name: grafanadb
          mountPath: /var/lib/grafana
      containers:
        - name: {{ .Chart.Name }}-grafana
          image: {{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: {{ .Values.grafana.resources.requests.cpu }}
              memory: {{ .Values.grafana.resources.requests.memory }}
          ports:
            - containerPort: 3000
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: "/api/health"
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          env:
          - name: GF_SERVER_DOMAIN
            value: {{ .Values.grafana.domain_name }}
          - name: GF_SERVER_ROOT_URL
            value: https://{{ .Values.grafana.domain_name }}
          - name: GF_SMTP_ENABLED
            value: "true"
          - name: GF_SMTP_HOST
            value: {{ .Values.grafana.smtp.host }}
          - name: GF_SMTP_USER
            value: {{ .Values.grafana.smtp.user }}
          - name: GF_SMTP_SKIP_VERIFY
            value: "false"
          - name: GF_SMTP_FROM_ADDRESS
            value: {{ .Values.grafana.smtp.from_address }}
          - name: GF_SMTP_FROM_NAME
            value: {{ .Values.grafana.smtp.from_name }}
          - name: GF_USERS_USER_INVITE_MAX_LIFETIME_DURATION
            value: "30d"
          - name: GF_AUTH_OAUTH_ALLOW_INSECURE_EMAIL_LOOKUO
            value: "true"
          - name: GF_OAUTH_SKIP_ORG_ROLE_UPDATE_SYNC
            value: "true"
          envFrom:
            - secretRef:
                name: {{ include "sheerwater-benchmarking.fullname" . }}-grafana-secrets
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafanadb
      volumes:
        - name: grafanadb
          persistentVolumeClaim:
            claimName: {{ include "sheerwater-benchmarking.fullname" . }}-grafana 
