apiVersion: v1
kind: Service
metadata:
  name: {{ include "sheerwater-benchmarking.fullname" . }}-grafana
  labels:
    app: {{ include "sheerwater-benchmarking.name" . }}-grafana
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: {{ include "sheerwater-benchmarking.name" . }}-grafana
    release: {{ .Release.Name }}
