apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sheerwater-benchmarking.fullname" . }}-postgres
  labels:
    app: {{ include "sheerwater-benchmarking.name" . }}-postgres
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "sheerwater-benchmarking.name" . }}-postgres
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        timestamp: '{{ now | date "2006-01-02T15:04:05" }}'
      labels:
        app: {{ include "sheerwater-benchmarking.name" . }}-postgres
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-postgres
          image: {{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: {{ .Values.postgres.resources.requests.cpu }}
              memory: {{ .Values.postgres.resources.requests.memory }}
          ports:
            - containerPort: 5432
          env:
          - name: PGDATA
            value: /var/lib/postgresql/data
          envFrom:
            - secretRef:
                name: {{ include "sheerwater-benchmarking.fullname" . }}-postgres-secrets
          volumeMounts:
            - mountPath: /var/lib/postgresql/
              name: postgresdb
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: {{ include "sheerwater-benchmarking.fullname" . }}-postgres 
