apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: {{ include "sheerwater-benchmarking.name" . }}-postgress
    release: {{ .Release.Name }}
  annotations:
    tailscale.com/expose: "true"
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: {{ include "sheerwater-benchmarking.name" . }}-postgres
    release: {{ .Release.Name }}
