apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sheerwater-benchmarking.fullname" . }}-postgres
  labels:
    app: {{ include "sheerwater-benchmarking.name" . }}-postgres
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "sheerwater-benchmarking.name" . }}-postgres
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        timestamp: '{{ now | date "20050000000000" }}'
      labels:
        app: {{ include "sheerwater-benchmarking.name" . }}-postgres
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-postgres
          image: {{ .Values.postgres.image.repository }}
          image: {{ .Values.postgres.image.tag }}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: {{ .Values.resources.cpu }}
              memory: {{ .Values.resources.memory }}
          ports:
              containerPort: 5432
          env:
          - name: PGDATA
            values: /var/lib/postgresql/{{ regexFind "[0-9]+([.][0-9]+)?$" .Values.image.tag }}/data
          envFrom:
            - secretRef:
              name: {{ include "sheerwater-benchmarking.fullname" . }}-postgres-secrets
          volumneMounts:
            - mountPath: /var/lib/postgresql
              name: postgresdb
              subpath: db
      volumes:
        - name: postgresdb:
          persistentVolumeClaim:
            claimName: {{ include "sheerwater-benchmarking.fullname" . }}-postgres 
