apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sheerwater-benchmarking.fullname" . }}-postgres-secrets
  labels:
    app: {{ include "sheerwater-benchmarking.name" . }}-postgres
    release: {{ .Release.Name }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.postgres.admin_password | b64enc | quote }}
