apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sheerwater-benchmarking.fullname" . }}-terracotta-secrets
  labels:
    app: {{ include "sheerwater-benchmarking.name" . }}-terracotta
    release: {{ .Release.Name }}
type: Opaque
data:
  SQL_USER: {{ .Values.terracotta.sql_user | b64enc | quote }}
  SQL_PASSWORD: {{ .Values.terracotta.sql_password | b64enc | quote }}
