apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sheerwater-benchmarking.fullname" . }}-terracotta
  labels:
    app: {{ include "sheerwater-benchmarking.name" . }}-terracotta
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "sheerwater-benchmarking.name" . }}-terracotta
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        timestamp: '{{ now | date "2006-01-02T15:04:05" }}'
      labels:
        app: {{ include "sheerwater-benchmarking.name" . }}-terracotta
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-terracotta
          image: {{ .Values.terracotta.image.repository }}:{{ .Values.terracotta.image.tag }}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: {{ .Values.terracotta.resources.requests.cpu }}
              memory: {{ .Values.terracotta.resources.requests.memory }}
          ports:
            - containerPort: 5000
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: "/keys"
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          env:
          - name: TC_DRIVER_PATH
            value: {{ .Values.terracotta.driver_path }}
          - name: TC_DEBUG
            value: "true"
          - name: TC_LOG_LEVEL
            value: "debug"
          - name: TC_FLASK_PROFILE
            value: "true"
          - name: TC_RESAMPLING_METHOD
            value: "nearest"
          - name: TC_REPROJECTION_METHOD
            value: "nearest"
          - name: TC_ALLOWED_ORIGINS_TILES
            value: '["*"]'
          - name: TC_RASTER_CACHE_SIZE
            # Size of raster file in-memory cache, in bytes
            value: 513802240
          - name: TC_RASTER_CACHE_COMPRESS_LEVEL
            # Compression level of raster file in-memory cache, from 0-9
            value: 9
          envFrom:
            - secretRef:
                name: {{ include "sheerwater-benchmarking.fullname" . }}-terracotta-secrets
          volumeMounts:
            - mountPath: /mnt/sheerwater-datalake
              name: terracotta-rasters
      serviceAccountName: sheerwater-sa
      volumes:
        - name: terracotta-rasters
          persistentVolumeClaim:
            claimName: {{ include "sheerwater-benchmarking.fullname" . }}-terracotta 
