apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "sheerwater-benchmarking.fullname" . }}-terracotta-pv-{{ .Release.Namespace }}
  labels:
    app: {{ include "sheerwater-benchmarking.name" . }}-terracotta
    release: {{ .Release.Name }}
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: {{ .Values.terracotta.pv.size }}
  gcePersistentDisk:
    pdName: {{ .Values.terracotta.pv.name }}
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sheerwater-benchmarking.fullname" . }}-terracotta
  labels:
    app: {{ include "sheerwater-benchmarking.name" . }}-terracotta
    release: {{ .Release.Name }}
spec:
  storageClassName: ""
  volumeName: {{ include "sheerwater-benchmarking.fullname" . }}-terracotta-pv-{{ .Release.Namespace }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.terracotta.pv.size }}

