# This Deployment manages multiple Terracotta pods with read-only access to raster data.
# The data synchronization is handled by a separate CronJob that runs every 30 minutes.
#
# Key features:
# 1. All pods are identical read-only replicas
# 2. Horizontal scaling with consistent read-only access
#
# Data consistency is maintained through the separate sync CronJob (single writer)
# while all Terracotta pods have read-only access to the data.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sheerwater-benchmarking.fullname" . }}-terracotta
  labels:
    app: {{ include "sheerwater-benchmarking.name" . }}-terracotta
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.terracotta.replicas }}
  selector:
    matchLabels:
      app: {{ include "sheerwater-benchmarking.name" . }}-terracotta
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        timestamp: '{{ now | date "2006-01-02T15:04:05" }}'
      labels:
        app: {{ include "sheerwater-benchmarking.name" . }}-terracotta
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-terracotta
          image: {{ .Values.terracotta.image.repository }}:{{ .Values.terracotta.image.tag }}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: {{ .Values.terracotta.resources.requests.cpu }}
              memory: {{ .Values.terracotta.resources.requests.memory }}
            limits:
              cpu: {{ .Values.terracotta.resources.limits.cpu }}
              memory: {{ .Values.terracotta.resources.limits.memory }}
          ports:
            - containerPort: 5000
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: "/keys"
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          env:
          - name: TC_DRIVER_PATH
            value: {{ .Values.terracotta.driver_path }}
          - name: TC_DEBUG
            value: "true"
          - name: TC_LOG_LEVEL
            value: "debug"
          - name: TC_FLASK_PROFILE
            value: "true"
          - name: TC_RESAMPLING_METHOD
            value: "nearest"
          - name: TC_REPROJECTION_METHOD
            value: "nearest"
          - name: TC_ALLOWED_ORIGINS_TILES
            value: '["*"]'
          - name: TC_RASTER_CACHE_SIZE
            value: {{ .Values.terracotta.raster_cache_size | int | quote }}
          - name: TC_RASTER_CACHE_COMPRESS_LEVEL
            value: {{ .Values.terracotta.raster_cache_compress_level | int | quote }}
          - name: TC_MULTIPROCESSING_WORKERS
            value: "{{ .Values.terracotta.multiprocessing_workers }}"
          envFrom:
            - secretRef:
                name: {{ include "sheerwater-benchmarking.fullname" . }}-terracotta-secrets
          volumeMounts:
            - mountPath: /mnt/sheerwater-datalake
              name: terracotta-rasters
              readOnly: true  # All Terracotta containers are read-only
      serviceAccountName: sheerwater-sa
      volumes:
        - name: terracotta-rasters
          persistentVolumeClaim:
            claimName: {{ include "sheerwater-benchmarking.fullname" . }}-terracotta
