apiVersion: v1
kind: Service
metadata:
  name: terracotta
  labels:
    app: {{ include "sheerwater-benchmarking.name" . }}-terracotta
    release: {{ .Release.Name }}
  annotations:
    tailscale.com/expose: "true"
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: {{ include "sheerwater-benchmarking.name" . }}-terracotta
    release: {{ .Release.Name }}
