# This configuration creates two PersistentVolumes that point to the same GCP disk:
# 1. A read-write PV for the sync job
# 2. A read-only PV for all Terracotta containers
#
# Both PVs use the same underlying GCP disk, but with different access modes:
# - Sync: ReadWriteOnce to ensure only the sync job can write
# - Terracotta: ReadOnlyMany to allow all Terracotta containers to read

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "sheerwater-benchmarking.fullname" . }}-terracotta-sync-pv-{{ .Release.Namespace }}
  labels:
    app: {{ include "sheerwater-benchmarking.name" . }}-terracotta
    release: {{ .Release.Name }}
spec:
  accessModes:
  - ReadWriteOnce  # Only sync job can write
  capacity:
    storage: {{ .Values.terracotta.pv.size }}
  gcePersistentDisk:
    pdName: {{ .Values.terracotta.pv.name }}
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "sheerwater-benchmarking.fullname" . }}-terracotta-pv-{{ .Release.Namespace }}
  labels:
    app: {{ include "sheerwater-benchmarking.name" . }}-terracotta
    release: {{ .Release.Name }}
spec:
  accessModes:
  - ReadOnlyMany  # All Terracotta containers read-only
  capacity:
    storage: {{ .Values.terracotta.pv.size }}
  gcePersistentDisk:
    pdName: {{ .Values.terracotta.pv.name }}  # Same disk as sync PV
    fsType: ext4
    readOnly: true  # Enforce read-only at the disk level
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sheerwater-benchmarking.fullname" . }}-terracotta
  labels:
    app: {{ include "sheerwater-benchmarking.name" . }}-terracotta
    release: {{ .Release.Name }}
spec:
  storageClassName: ""
  volumeName: {{ include "sheerwater-benchmarking.fullname" . }}-terracotta-pv-{{ .Release.Namespace }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.terracotta.pv.size }}

