apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "sheerwater-benchmarking.fullname" . }}-timescale-pv-{{ .Release.Namespace }}
  labels:
    app: {{ include "sheerwater-benchmarking.name" . }}-timescale
    release: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.timescale.pv.size }}
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: {{ .Values.timescale.pv.name }}
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sheerwater-benchmarking.fullname" . }}-timescale
  labels:
    app: {{ include "sheerwater-benchmarking.name" . }}-timescale
    release: {{ .Release.Name }}
spec:
  storageClassName: ""
  volumeName: {{ include "sheerwater-benchmarking.fullname" . }}-timescale-pv-{{ .Release.Namespace }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.timescale.pv.size }}

