apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sheerwater-benchmarking.fullname" . }}-timescale
  labels:
    app: {{ include "sheerwater-benchmarking.name" . }}-timescale
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "sheerwater-benchmarking.name" . }}-timescale
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        timestamp: '{{ now | date "2006-01-02T15:04:05" }}'
      labels:
        app: {{ include "sheerwater-benchmarking.name" . }}-timescale
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-timescale
          image: {{ .Values.timescale.image.repository }}:{{ .Values.timescale.image.tag }}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: {{ .Values.timescale.resources.requests.cpu }}
              memory: {{ .Values.timescale.resources.requests.memory }}
          ports:
            - containerPort: 5432
          env:
          - name: PGDATA
            value: /var/lib/postgresql/data/db
          envFrom:
            - secretRef:
                name: {{ include "sheerwater-benchmarking.fullname" . }}-timescale-secrets
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: timescaledb
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 1000
      volumes:
        - name: timescaledb
          persistentVolumeClaim:
            claimName: {{ include "sheerwater-benchmarking.fullname" . }}-timescale 
