apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sheerwater-benchmarking.fullname" . }}-timescale-secrets
  labels:
    app: {{ include "sheerwater-benchmarking.name" . }}-timescale
    release: {{ .Release.Name }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.timescale.admin_password | b64enc | quote }}
