name: Terraform apply for main/prod

on:
  push:
    branches:
      - main

concurrency:
  group: tf-grafana-main
  cancel-in-progress: false

env:
  TF_IN_AUTOMATION: "true"

jobs:
  apply:
    name: Apply terraform for main/prod
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        shell: bash
        working-directory: ./infrastructure/terraform-config
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: "projects/730596460290/locations/global/workloadIdentityPools/rhiza-github/providers/rhiza-github"
          service_account: "rhiza-github-action@rhiza-shared.iam.gserviceaccount.com"
          export_environment_variables: true

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init 
        run: terraform init -input=false

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve
